name: cabal build

on:
  push:
    paths:
    - 'src/**'
    - 'Agda.cabal'
    - 'cabal.project'
    - '.github/workflows/cabal.yml'
  pull_request:
    paths:
    - 'src/**'
    - 'Agda.cabal'
    - 'cabal.project'
    - '.github/workflows/cabal.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghc-ver: ["8.8.3"]
        cabal-ver: ["3.0"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      name: Cache dependencies
      with:
        path: "~/.cabal"
        key: ${{ runner.os }}-ghc-${{ matrix.ghc-ver }}-cabal-${{ matrix.cabal-ver }}
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc-ver }}
        cabal-version: ${{ matrix.cabal-ver }}

    - name: Install dependencies
      run: |
        cabal new-update
        cabal new-configure -O0
        cabal new-install --only-dependencies
    - name: Build Agda
      run: |
        cabal new-build -j

    - name: Upload Agda artefact
      uses: actions/upload-artifact@v1
      with:
        name: agda-binary
        path: dist-newstyle

  quick-test:

    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        ghc-ver: ["8.8.3"]
        cabal-ver: ["3.0"]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      name: Cache dependencies
      with:
        path: "~/.cabal"
        key: ${{ runner.os }}-ghc-${{ matrix.ghc-ver }}-cabal-${{ matrix.cabal-ver }}

    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc-ver }}
        cabal-version: ${{ matrix.cabal-ver }}

    - uses: actions/download-artifact@v1
      with:
        name: agda-binary
        path: dist-newstyle
    - name: Check the existence of Agda
      run: |
        cabal exec -- which agda

