name: Whitespace
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: '8.8.3'
          cabal-version: '3.0'
      - name: Install fix-agda-whitespace
        run: |
          cabal update
          cd src/fix-agda-whitespace/
          cabal install
          cd ../..
      - name: Check the whitespace issue
        run: |
          $HOME/.cabal/bin/fix-agda-whitespace --check
